I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 34, in script
    if wake == 1:
  File "game/prologue.rpy", line 34, in <module>
    if wake == 1:
NameError: name 'wake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 34, in script
    if wake == 1:
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/python.py", line 1725, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/python.py", line 1719, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/prologue.rpy", line 34, in <module>
    if wake == 1:
NameError: name 'wake' is not defined

Darwin-16.4.0-x86_64-i386-64bit
Ren'Py 6.99.12.2.2029
WIP 0.01
